require("prototypes.categories")
require("prototypes.entity.meltdown-facility")
require("prototypes.entity.downgrade-port")
require("prototypes.item")
require("prototypes.quality")
require("prototypes.recipe")
require("prototypes.entity.entity")
