data:extend({
	{
		type = "quality",
		name = "shoddy",
		level = -1,
		color = { 55, 55, 21 },
		order = "d",
		next = "defective",
		next_probability = 0.1,
		subgroup = "qualities",
		icon = "__Inverted-Quality__/graphics/icons/2.png",
		beacon_power_usage_multiplier = 1,
		mining_drill_resource_drain_multiplier = 1,
		science_pack_drain_multiplier = 1,
	},
	{
		type = "quality",
		name = "defective",
		level = -3,
		color = { 82, 43, 15 },
		order = "c",
		next = "broken",
		next_probability = 0.1,
		subgroup = "qualities",
		icon = "__Inverted-Quality__/graphics/icons/3.png",
		beacon_power_usage_multiplier = 1,
		mining_drill_resource_drain_multiplier = 1,
		science_pack_drain_multiplier = 1,
	},
	{
		type = "quality",
		name = "broken",
		level = -3,
		color = { 96, 11, 16 },
		order = "b",
		subgroup = "qualities",
		icon = "__Inverted-Quality__/graphics/icons/4.png",
		beacon_power_usage_multiplier = 1,
		mining_drill_resource_drain_multiplier = 1,
		science_pack_drain_multiplier = 1,
	},
})
