data:extend({
	{
		type = "quality",
		name = "scuffed",
		level = -1,
		color = { 55, 55, 21 },
		order = "b",
		next = "funky",
		next_probability = 0.1,
		subgroup = "qualities",
		icon = "__Inverted-Quality__/graphics/icons/scuffed.png",
		beacon_power_usage_multiplier = 1,
		mining_drill_resource_drain_multiplier = 1,
		science_pack_drain_multiplier = 1,
	},
	{
		type = "quality",
		name = "funky",
		level = -2,
		color = { 82, 43, 15 },
		order = "c",
		next = "defective",
		next_probability = 0.1,
		subgroup = "qualities",
		icon = "__Inverted-Quality__/graphics/icons/funky.png",
		beacon_power_usage_multiplier = 1,
		mining_drill_resource_drain_multiplier = 1,
		science_pack_drain_multiplier = 1,
	},
	{
		type = "quality",
		name = "defective",
		level = -3,
		color = { 96, 11, 16 },
		order = "d",
		next = "broken",
		next_probability = 0.1,
		subgroup = "qualities",
		icon = "__Inverted-Quality__/graphics/icons/defective.png",
		beacon_power_usage_multiplier = 1,
		mining_drill_resource_drain_multiplier = 1,
		science_pack_drain_multiplier = 1,
	},
	{
		type = "quality",
		name = "broken",
		level = -5,
		color = { 53, 31, 25 },
		order = "e",
		subgroup = "qualities",
		icon = "__Inverted-Quality__/graphics/icons/broken.png",
		beacon_power_usage_multiplier = 1,
		mining_drill_resource_drain_multiplier = 1,
		science_pack_drain_multiplier = 1,
		-- hidden = true,
	},
})

-- data:extend({
-- 	{
-- 		type = "quality",
-- 		name = "worn",
-- 		level = 7.5,
-- 		color = { 227, 224, 84 },
-- 		order = "aa-d",
-- 		next = "shoddy",
-- 		next_probability = 0.1,
-- 		subgroup = "qualities",
-- 		icon = "__Inverted-Quality__/graphics/icons/degradation-2.png",
-- 		-- beacon_power_usage_multiplier
-- 		-- mining_drill_resource_drain_multiplier
-- 		-- science_pack_drain_multiplier
-- 	},
-- 	{
-- 		type = "quality",
-- 		name = "shoddy",
-- 		level = 5,
-- 		color = { 205, 123, 46 },
-- 		order = "aa-c",
-- 		next = "degraded",
-- 		next_probability = 0.1,
-- 		subgroup = "qualities",
-- 		icon = "__Inverted-Quality__/graphics/icons/degradation-3.png",
-- 	},
-- 	{
-- 		type = "quality",
-- 		name = "degraded",
-- 		level = 2.5,
-- 		color = { 146, 24, 24 },
-- 		order = "aa-b",
-- 		next = "faulty",
-- 		next_probability = 0.1,
-- 		subgroup = "qualities",
-- 		icon = "__Inverted-Quality__/graphics/icons/degradation-4.png",
-- 	},
-- 	{
-- 		type = "quality",
-- 		name = "faulty",
-- 		level = 0,
-- 		color = { 34, 34, 34 },
-- 		order = "aa-a",
-- 		subgroup = "qualities",
-- 		icon = "__Inverted-Quality__/graphics/icons/degradation-5.png",
-- 	},
-- })
